# GitHub Action for PHP Plugins Markdown Parse from Bear
name: Testing PHP Plugins Markdown Parse from Bear
on: [ push, pull_request ]
jobs:
    build:
        strategy:
            matrix:
                operating-system: [ ubuntu-latest, macos-latest ]
                php-versions: [ '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
        runs-on: ${{ matrix.operating-system }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v2 # From https://github.com/shivammathur/setup-php
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: mbstring, intl, curl, json, openssl, iconv
                    coverage: xdebug #optional
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader